# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"7\n\x06\x43oding\x12\x0e\n\x06system\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07\x64isplay\x18\x03 \x01(\t\"?\n\x0f\x43odeableConcept\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1e\n\x06\x63oding\x18\x02 \x03(\x0b\x32\x0e.common.Coding\"+\n\nIdentifier\x12\x0e\n\x06system\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"/\n\tReference\x12\x11\n\treference\x18\x01 \x01(\t\x12\x0f\n\x07\x64isplay\x18\x02 \x01(\t\":\n\tHumanName\x12\x0e\n\x06\x66\x61mily\x18\x01 \x01(\t\x12\r\n\x05given\x18\x02 \x03(\t\x12\x0e\n\x06prefix\x18\x03 \x03(\t\":\n\x0c\x43ontactPoint\x12\x0e\n\x06system\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0b\n\x03use\x18\x03 \x01(\tB\x19\xaa\x02\x16\x46hirGrpcGateway.Serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\026FhirGrpcGateway.Server'
  _globals['_CODING']._serialized_start=24
  _globals['_CODING']._serialized_end=79
  _globals['_CODEABLECONCEPT']._serialized_start=81
  _globals['_CODEABLECONCEPT']._serialized_end=144
  _globals['_IDENTIFIER']._serialized_start=146
  _globals['_IDENTIFIER']._serialized_end=189
  _globals['_REFERENCE']._serialized_start=191
  _globals['_REFERENCE']._serialized_end=238
  _globals['_HUMANNAME']._serialized_start=240
  _globals['_HUMANNAME']._serialized_end=298
  _globals['_CONTACTPOINT']._serialized_start=300
  _globals['_CONTACTPOINT']._serialized_end=358
# @@protoc_insertion_point(module_scope)
