# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fhir_patient.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fhir_patient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66hir_patient.proto\x12\x04\x66hir\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"y\n\x0ePatientRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x11\n\tbirthDate\x18\x04 \x01(\t\x12*\n\x07telecom\x18\x05 \x03(\x0b\x32\x19.fhir.ContactPointMessage\"\x9b\x01\n\x14PatientSearchRequest\x12\x13\n\x0b\x66\x61mily_name\x18\x01 \x01(\t\x12\x12\n\ngiven_name\x18\x02 \x01(\t\x12\x12\n\nidentifier\x18\x03 \x01(\t\x12\x18\n\x10\x62irthdate_before\x18\x04 \x01(\t\x12\x17\n\x0f\x62irthdate_after\x18\x05 \x01(\t\x12\x13\n\x0b\x61\x63tive_only\x18\x06 \x01(\x08\"\x8a\x01\n\x0fPatientResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x11\n\tbirthDate\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12*\n\x07telecom\x18\x06 \x03(\x0b\x32\x19.fhir.ContactPointMessage\">\n\x13PatientListResponse\x12\'\n\x08patients\x18\x01 \x03(\x0b\x32\x15.fhir.PatientResponse\"A\n\x13\x43ontactPointMessage\x12\x0e\n\x06system\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0b\n\x03use\x18\x03 \x01(\t\"B\n\x16ResourceBundleResponse\x12\x15\n\rresource_type\x18\x01 \x01(\t\x12\x11\n\tjson_data\x18\x02 \x01(\t2\xd7\x03\n\nPatientApi\x12\x39\n\nGetPatient\x12\x14.fhir.PatientRequest\x1a\x15.fhir.PatientResponse\x12\x41\n\x0cListPatients\x12\x16.google.protobuf.Empty\x1a\x19.fhir.PatientListResponse\x12<\n\rCreatePatient\x12\x14.fhir.PatientRequest\x1a\x15.fhir.PatientResponse\x12<\n\rDeletePatient\x12\x14.fhir.PatientRequest\x1a\x15.fhir.PatientResponse\x12G\n\x0eSearchPatients\x12\x1a.fhir.PatientSearchRequest\x1a\x19.fhir.PatientListResponse\x12\x45\n\rGetEverything\x12\x14.fhir.PatientRequest\x1a\x1c.fhir.ResourceBundleResponse0\x01\x12?\n\x0cMatchPatient\x12\x14.fhir.PatientRequest\x1a\x19.fhir.PatientListResponseB \xaa\x02\x1d\x46hirGrpcGateway.Server.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fhir_patient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\035FhirGrpcGateway.Server.Protos'
  _globals['_PATIENTREQUEST']._serialized_start=71
  _globals['_PATIENTREQUEST']._serialized_end=192
  _globals['_PATIENTSEARCHREQUEST']._serialized_start=195
  _globals['_PATIENTSEARCHREQUEST']._serialized_end=350
  _globals['_PATIENTRESPONSE']._serialized_start=353
  _globals['_PATIENTRESPONSE']._serialized_end=491
  _globals['_PATIENTLISTRESPONSE']._serialized_start=493
  _globals['_PATIENTLISTRESPONSE']._serialized_end=555
  _globals['_CONTACTPOINTMESSAGE']._serialized_start=557
  _globals['_CONTACTPOINTMESSAGE']._serialized_end=622
  _globals['_RESOURCEBUNDLERESPONSE']._serialized_start=624
  _globals['_RESOURCEBUNDLERESPONSE']._serialized_end=690
  _globals['_PATIENTAPI']._serialized_start=693
  _globals['_PATIENTAPI']._serialized_end=1164
# @@protoc_insertion_point(module_scope)
