# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fhir_observation_pb2 as fhir__observation__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fhir_observation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObservationApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPatientObservations = channel.unary_unary(
                '/ObservationApi/GetPatientObservations',
                request_serializer=fhir__observation__pb2.ObservationRequest.SerializeToString,
                response_deserializer=fhir__observation__pb2.ObservationListResponse.FromString,
                _registered_method=True)


class ObservationApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPatientObservations(self, request, context):
        """Supports date filtering and pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObservationApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPatientObservations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientObservations,
                    request_deserializer=fhir__observation__pb2.ObservationRequest.FromString,
                    response_serializer=fhir__observation__pb2.ObservationListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ObservationApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ObservationApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObservationApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPatientObservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ObservationApi/GetPatientObservations',
            fhir__observation__pb2.ObservationRequest.SerializeToString,
            fhir__observation__pb2.ObservationListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
