# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fhir_patient_pb2 as fhir__patient__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fhir_patient_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatientApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPatient = channel.unary_unary(
                '/fhir.PatientApi/GetPatient',
                request_serializer=fhir__patient__pb2.PatientRequest.SerializeToString,
                response_deserializer=fhir__patient__pb2.PatientResponse.FromString,
                _registered_method=True)
        self.ListPatients = channel.unary_unary(
                '/fhir.PatientApi/ListPatients',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fhir__patient__pb2.PatientListResponse.FromString,
                _registered_method=True)
        self.CreatePatient = channel.unary_unary(
                '/fhir.PatientApi/CreatePatient',
                request_serializer=fhir__patient__pb2.PatientRequest.SerializeToString,
                response_deserializer=fhir__patient__pb2.PatientResponse.FromString,
                _registered_method=True)
        self.DeletePatient = channel.unary_unary(
                '/fhir.PatientApi/DeletePatient',
                request_serializer=fhir__patient__pb2.PatientRequest.SerializeToString,
                response_deserializer=fhir__patient__pb2.PatientResponse.FromString,
                _registered_method=True)
        self.SearchPatients = channel.unary_unary(
                '/fhir.PatientApi/SearchPatients',
                request_serializer=fhir__patient__pb2.PatientSearchRequest.SerializeToString,
                response_deserializer=fhir__patient__pb2.PatientListResponse.FromString,
                _registered_method=True)
        self.GetEverything = channel.unary_stream(
                '/fhir.PatientApi/GetEverything',
                request_serializer=fhir__patient__pb2.PatientRequest.SerializeToString,
                response_deserializer=fhir__patient__pb2.ResourceBundleResponse.FromString,
                _registered_method=True)
        self.MatchPatient = channel.unary_unary(
                '/fhir.PatientApi/MatchPatient',
                request_serializer=fhir__patient__pb2.PatientRequest.SerializeToString,
                response_deserializer=fhir__patient__pb2.PatientListResponse.FromString,
                _registered_method=True)


class PatientApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPatients(self, request, context):
        """Added
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePatient(self, request, context):
        """Added
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePatient(self, request, context):
        """Added
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPatients(self, request, context):
        """Advanced Search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEverything(self, request, context):
        """$everything Operation (Server Streaming for Large records)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchPatient(self, request, context):
        """$match (MPI Lookup)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatient,
                    request_deserializer=fhir__patient__pb2.PatientRequest.FromString,
                    response_serializer=fhir__patient__pb2.PatientResponse.SerializeToString,
            ),
            'ListPatients': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPatients,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fhir__patient__pb2.PatientListResponse.SerializeToString,
            ),
            'CreatePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePatient,
                    request_deserializer=fhir__patient__pb2.PatientRequest.FromString,
                    response_serializer=fhir__patient__pb2.PatientResponse.SerializeToString,
            ),
            'DeletePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePatient,
                    request_deserializer=fhir__patient__pb2.PatientRequest.FromString,
                    response_serializer=fhir__patient__pb2.PatientResponse.SerializeToString,
            ),
            'SearchPatients': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPatients,
                    request_deserializer=fhir__patient__pb2.PatientSearchRequest.FromString,
                    response_serializer=fhir__patient__pb2.PatientListResponse.SerializeToString,
            ),
            'GetEverything': grpc.unary_stream_rpc_method_handler(
                    servicer.GetEverything,
                    request_deserializer=fhir__patient__pb2.PatientRequest.FromString,
                    response_serializer=fhir__patient__pb2.ResourceBundleResponse.SerializeToString,
            ),
            'MatchPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchPatient,
                    request_deserializer=fhir__patient__pb2.PatientRequest.FromString,
                    response_serializer=fhir__patient__pb2.PatientListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fhir.PatientApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fhir.PatientApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fhir.PatientApi/GetPatient',
            fhir__patient__pb2.PatientRequest.SerializeToString,
            fhir__patient__pb2.PatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fhir.PatientApi/ListPatients',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fhir__patient__pb2.PatientListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fhir.PatientApi/CreatePatient',
            fhir__patient__pb2.PatientRequest.SerializeToString,
            fhir__patient__pb2.PatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fhir.PatientApi/DeletePatient',
            fhir__patient__pb2.PatientRequest.SerializeToString,
            fhir__patient__pb2.PatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fhir.PatientApi/SearchPatients',
            fhir__patient__pb2.PatientSearchRequest.SerializeToString,
            fhir__patient__pb2.PatientListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEverything(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fhir.PatientApi/GetEverything',
            fhir__patient__pb2.PatientRequest.SerializeToString,
            fhir__patient__pb2.ResourceBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MatchPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fhir.PatientApi/MatchPatient',
            fhir__patient__pb2.PatientRequest.SerializeToString,
            fhir__patient__pb2.PatientListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
